zmodload zsh/zprof

# zsh options
setopt GLOB_COMPLETE
setopt AUTO_CD
export SAVEHIST=5000
export HISTSIZE=2000
setopt EXTENDED_HISTORY
setopt SHARE_HISTORY
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_FIND_NO_DUPS
setopt HIST_REDUCE_BLANKS
setopt CORRECT
setopt CORRECT_ALL

export PATH="$HOME/bin:$HOME/.local/bin:/usr/local/bin:/usr/local/sbin:$PATH"

#export PATH="$PATH:$HOME/bin/flutter/bin"

export LANG=en_US.UTF-8
#
APPLE_SSH_ADD_BEHAVIOR='macos'

# AWS CLI environment configuration
AWS_CLI_AUTO_PROMPT='on'
AWS_PAGER='fx'

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='vim'
else
   export EDITOR='code'
fi

alias brew='env PATH=${PATH//$(pyenv root)\/shims:/} brew'
#alias ls="ls --color=always"
alias grep="grep --color=always"
alias egrep="egrep --color=always"
alias brewup="brew update && brew upgrade && brew cleanup"
alias -s md="code"
alias ec="$EDITOR $HOME/.zshrc"


if [ "$(command -v exa)" ]; then
   unalias -m 'll'
   unalias -m 'l'
   unalias -m 'la'
   unalias -m 'ls'
   alias ls='exa -G --color auto -s type'
   alias ll='exa -lh --color auto -s type'
   alias la='exa -lh --color auto -a -s type'
fi

if [ "$(command -v bat)" ]; then
   unalias -m 'cat'
   alias cat='bat -pp --theme="Nord"'
fi

MODE_INDICATOR_VIINS='%F{15}<%F{8}INSERT<%f'
MODE_INDICATOR_VICMD='%F{10}<%F{2}NORMAL<%f'
MODE_INDICATOR_REPLACE='%F{9}<%F{1}REPLACE<%f'
MODE_INDICATOR_SEARCH='%F{13}<%F{5}SEARCH<%f'
MODE_INDICATOR_VISUAL='%F{12}<%F{4}VISUAL<%f'
MODE_INDICATOR_VLINE='%F{12}<%F{4}V-LINE<%f'

source "${HOME}/.zgen/zgen.zsh"

fpath=( ~/.zfunc $fpath )
autoload -Uz ~/.zfunc/**/*

bindkey -rpM viins '^[^['
bindkey '^[[H' beginning-of-line
bindkey '^[[F' end-of-line

export JAVA_TOOLS_OPTIONS="-Dlog4j2.formatMsgNoLookups=true"


eval "$(starship init zsh)"
